### PR TITLE
No default db setting

### LINKED ISSUE #6: Default setting for uaadb and ccdb
The default scheme for uaadb and ccdb is MySql, in codex we are using PostgreSql, what do you think we remove this default setting , then in codex we add that we need to configure uaadb and ccdb scheme? 

This will save us some time in the scenario that customer not using MySql (default setting now), we have to deploy CF, then uaa vm failed, then we debug and find out wrong db scheme is configured and deploy it again

### PR DESCRIPTION
**Pull request by xiujiao**
@jhunt @norman-abramovitz Could you please take a look? This resolves https://github.com/starkandwayne/cf-deployment/issues/6

### CODE REVIEW

**Comment by norman-abramovitz** [comment]
Are there any needs to improve the documentation now that the databases not being set.   I am assuming somewhere else the database properties are being set.   It is not clear from the commits where that would be.

**Comment by xiujiao** [comment]
@norman-abramovitz I added some doc about how to config dbs. To summarize the PR: removed default db scheme setting for aws, but still uses RDS; removed default db provision for Google, Vcloud, Openstack; Add Doc about configuring db connection info and scheme; keep Vsphere using postgres from S&W postgres release as an example when there is no RDS solution avaiable.

**Comment by geofffranks** [comment]
Why did we do this?

**Comment by xiujiao** [comment]
@geofffranks Originally it was because when we deployed it to AWS using RDS postgres for dbs, it failed since default setting for db is mysql, it took some time to debug and change db setting to make it work again,so I was thinking that if we do not set a default db scheme for aws db, then when we `make manifest` it will remind us to set correct scheme and port, then we can save some time since we do not need to go through the process of `deploy -> debug-> redeploy`. Although, it was also because I never read the READme when I deployed to AWS, otherwise I will see in the doc it was saying defaulting to mysql to save some time. Regarding to Google and Vcloud, probably we can keep it the same way with vsphere instead of leaving db part out.

**Pull request merged**
